### ISSUE TITLE
implement DomainSearch

### ISSUE THREAD

**Issue by tobsch** [NEXL-LTS/snov-ruby#5]
Hi there,

great - just discovered this fresh and shiny gem! nice work!
Do you have plans to add this endpoint?
https://snov.io/api#DomainSearch2

Tobi

**Comment by grantspeelman** [comment]
sorry @tobsch , I only stumbled across this now.

We have implemented a version of domain search2: https://github.com/NEXL-LTS/snov-ruby#domainsearch

Better late than never I guess 😄
